# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/constraints/ARTY_Z7.xdc

# Block Designs: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/Arty_Z7_20.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20 || ORIG_REF_NAME==Arty_Z7_20}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_axi_dynclk_0_0/Arty_Z7_20_axi_dynclk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_axi_dynclk_0_0 || ORIG_REF_NAME==Arty_Z7_20_axi_dynclk_0_0}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_axi_gpio_hdmi_0/Arty_Z7_20_axi_gpio_hdmi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_axi_gpio_hdmi_0 || ORIG_REF_NAME==Arty_Z7_20_axi_gpio_hdmi_0}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_axi_gpio_led_0/Arty_Z7_20_axi_gpio_led_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_axi_gpio_led_0 || ORIG_REF_NAME==Arty_Z7_20_axi_gpio_led_0}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_axi_gpio_shield_1_0/Arty_Z7_20_axi_gpio_shield_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_axi_gpio_shield_1_0 || ORIG_REF_NAME==Arty_Z7_20_axi_gpio_shield_1_0}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_axi_gpio_shield_2_0/Arty_Z7_20_axi_gpio_shield_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_axi_gpio_shield_2_0 || ORIG_REF_NAME==Arty_Z7_20_axi_gpio_shield_2_0}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_axi_gpio_sw_0/Arty_Z7_20_axi_gpio_sw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_axi_gpio_sw_0 || ORIG_REF_NAME==Arty_Z7_20_axi_gpio_sw_0}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_axi_mem_intercon_0/Arty_Z7_20_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_axi_mem_intercon_0 || ORIG_REF_NAME==Arty_Z7_20_axi_mem_intercon_0}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_axis_subset_converter_0_0/Arty_Z7_20_axis_subset_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_axis_subset_converter_0_0 || ORIG_REF_NAME==Arty_Z7_20_axis_subset_converter_0_0}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_processing_system7_0_0/Arty_Z7_20_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_processing_system7_0_0 || ORIG_REF_NAME==Arty_Z7_20_processing_system7_0_0}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_processing_system7_0_axi_periph_0/Arty_Z7_20_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==Arty_Z7_20_processing_system7_0_axi_periph_0}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_rgb2dvi_0_0/Arty_Z7_20_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_rgb2dvi_0_0 || ORIG_REF_NAME==Arty_Z7_20_rgb2dvi_0_0}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_rst_processing_system7_0_100M_0/Arty_Z7_20_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==Arty_Z7_20_rst_processing_system7_0_100M_0}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_rst_processing_system7_0_142M_0/Arty_Z7_20_rst_processing_system7_0_142M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_rst_processing_system7_0_142M_0 || ORIG_REF_NAME==Arty_Z7_20_rst_processing_system7_0_142M_0}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_v_axi4s_vid_out_0_0/Arty_Z7_20_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==Arty_Z7_20_v_axi4s_vid_out_0_0}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_v_tc_0_0/Arty_Z7_20_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_v_tc_0_0 || ORIG_REF_NAME==Arty_Z7_20_v_tc_0_0}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_xadc_wiz_0_0/Arty_Z7_20_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_xadc_wiz_0_0 || ORIG_REF_NAME==Arty_Z7_20_xadc_wiz_0_0}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_xlconcat_0_0/Arty_Z7_20_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_xlconcat_0_0 || ORIG_REF_NAME==Arty_Z7_20_xlconcat_0_0}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_xlconcat_1_0/Arty_Z7_20_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_xlconcat_1_0 || ORIG_REF_NAME==Arty_Z7_20_xlconcat_1_0}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_xlconstant_0_0/Arty_Z7_20_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_xlconstant_0_0 || ORIG_REF_NAME==Arty_Z7_20_xlconstant_0_0}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_proc_sys_reset_0_0/Arty_Z7_20_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_proc_sys_reset_0_0 || ORIG_REF_NAME==Arty_Z7_20_proc_sys_reset_0_0}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_proc_sys_reset_0_1/Arty_Z7_20_proc_sys_reset_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_proc_sys_reset_0_1 || ORIG_REF_NAME==Arty_Z7_20_proc_sys_reset_0_1}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_clk_wiz_0_0/Arty_Z7_20_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_clk_wiz_0_0 || ORIG_REF_NAME==Arty_Z7_20_clk_wiz_0_0}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_proc_sys_reset_0_2/Arty_Z7_20_proc_sys_reset_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_proc_sys_reset_0_2 || ORIG_REF_NAME==Arty_Z7_20_proc_sys_reset_0_2}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_dvi2rgb_0_0/Arty_Z7_20_dvi2rgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_dvi2rgb_0_0 || ORIG_REF_NAME==Arty_Z7_20_dvi2rgb_0_0}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_v_vid_in_axi4s_0_0/Arty_Z7_20_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==Arty_Z7_20_v_vid_in_axi4s_0_0}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_proc_sys_reset_0_3/Arty_Z7_20_proc_sys_reset_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_proc_sys_reset_0_3 || ORIG_REF_NAME==Arty_Z7_20_proc_sys_reset_0_3}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_v_tc_1_0/Arty_Z7_20_v_tc_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_v_tc_1_0 || ORIG_REF_NAME==Arty_Z7_20_v_tc_1_0}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_axi_gpio_0_0/Arty_Z7_20_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_axi_gpio_0_0 || ORIG_REF_NAME==Arty_Z7_20_axi_gpio_0_0}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_xbar_0/Arty_Z7_20_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_xbar_0 || ORIG_REF_NAME==Arty_Z7_20_xbar_0}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_xbar_1/Arty_Z7_20_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_xbar_1 || ORIG_REF_NAME==Arty_Z7_20_xbar_1}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_axi_vdma_1_0/Arty_Z7_20_axi_vdma_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_axi_vdma_1_0 || ORIG_REF_NAME==Arty_Z7_20_axi_vdma_1_0}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_axi_vdma_0_1/Arty_Z7_20_axi_vdma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_axi_vdma_0_1 || ORIG_REF_NAME==Arty_Z7_20_axi_vdma_0_1}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_axis_subset_converter_1_0/Arty_Z7_20_axis_subset_converter_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_axis_subset_converter_1_0 || ORIG_REF_NAME==Arty_Z7_20_axis_subset_converter_1_0}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_auto_pc_1/Arty_Z7_20_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_auto_pc_1 || ORIG_REF_NAME==Arty_Z7_20_auto_pc_1}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_auto_pc_0/Arty_Z7_20_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_auto_pc_0 || ORIG_REF_NAME==Arty_Z7_20_auto_pc_0}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_s01_regslice_0/Arty_Z7_20_s01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_s01_regslice_0 || ORIG_REF_NAME==Arty_Z7_20_s01_regslice_0}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_s01_data_fifo_0/Arty_Z7_20_s01_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_s01_data_fifo_0 || ORIG_REF_NAME==Arty_Z7_20_s01_data_fifo_0}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_s00_regslice_0/Arty_Z7_20_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_s00_regslice_0 || ORIG_REF_NAME==Arty_Z7_20_s00_regslice_0}]

# IP: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/ip/Arty_Z7_20_s00_data_fifo_0/Arty_Z7_20_s00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Arty_Z7_20_s00_data_fifo_0 || ORIG_REF_NAME==Arty_Z7_20_s00_data_fifo_0}]

# XDC: /home/digilent/sam_work/git/sbobrowicz/Arty-Z7-20-base/src/bd/Arty_Z7_20/Arty_Z7_20_ooc.xdc
